version: "3.9"

x-fastbot-common: &fastbot-common
  network_mode: host
  restart: unless-stopped
  stdin_open: true
  tty: true
  environment:
    ROS_LOCALHOST_ONLY: "${ROS_LOCALHOST_ONLY:-0}"
    ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-0}"
    RMW_IMPLEMENTATION: "${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"

services:
  bringup:
    <<: *fastbot-common
    container_name: fastbot-bringup
    image: alanszpetmanski/alan.szpetmanski-cp22:fastbot-ros2-real
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/arduino_nano
      - /dev/ttyACM0:/dev/lslidar
      - /dev/video0:/dev/video0

  slam:
    <<: *fastbot-common
    container_name: fastbot-slam
    image: alanszpetmanski/alan.szpetmanski-cp22:fastbot-ros2-slam-real
    depends_on:
      - bringup

    volumes:
      - ../run_cartographer_real.sh:/scripts/run_cartographer_real.sh:ro

    environment:
      ROS_LOCALHOST_ONLY: "${ROS_LOCALHOST_ONLY:-0}"
      ROS_DOMAIN_ID: "${ROS_DOMAIN_ID:-0}"
      RMW_IMPLEMENTATION: "${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}"

      USE_SIM_TIME: "false"

      ODOM_TOPIC: "/fastbot/odom"
      SCAN_TOPIC: "/scan"

      TRACKING_FRAME: "base_link"
      PUBLISHED_FRAME: "base_link"
      ODOM_FRAME: "fastbot_odom"

      USE_ODOMETRY: "true"
      PROVIDE_ODOM_FRAME: "true"

      MAP_RESOLUTION: "0.05"
      MAP_PUBLISH_PERIOD: "1.0"

    command:
      - bash
      - /scripts/run_cartographer_real.sh
